# Generated by Django 3.2.5 on 2021-09-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internships',
            fields=[
                ('iid', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('duration', models.CharField(blank=True, max_length=200)),
                ('cpi', models.CharField(blank=True, max_length=200)),
                ('semester', models.CharField(max_length=100)),
                ('other_qualifications', models.TextField(blank=True)),
                ('stipend', models.FloatField(blank=True)),
            ],
        ),
    ]
