# Generated by Django 3.2.5 on 2021-09-21 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ezyaplyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internships',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
