# Generated by Django 3.2.5 on 2021-09-21 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ezyaplyapp', '0002_internships_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=200)),
                ('sem', models.CharField(max_length=200)),
                ('cpi', models.CharField(max_length=200)),
                ('precentage_10', models.CharField(max_length=200)),
                ('precentage_12', models.CharField(max_length=200)),
                ('resume', models.FileField(upload_to='')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezyaplyapp.internships')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
