# Generated by Django 3.2.5 on 2021-09-21 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ezyaplyapp', '0003_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='cpi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='internship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ezyaplyapp.internships'),
        ),
        migrations.AlterField(
            model_name='apply',
            name='phone_number',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='precentage_10',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='precentage_12',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='sem',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
