# Generated by Django 3.2.5 on 2021-09-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezyaplyapp', '0004_auto_20210921_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internships',
            name='cpi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='internships',
            name='date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='internships',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='internships',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='internships',
            name='other_qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internships',
            name='semester',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='internships',
            name='stipend',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
