# Generated by Django 3.2.5 on 2021-09-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ezyaplyapp', '0006_announcement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='date',
            new_name='announcement_date',
        ),
    ]
