# Generated by Django 3.2.5 on 2021-09-29 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ezyaplyapp', '0007_rename_date_announcement_announcement_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=200, null=True)),
                ('sem', models.CharField(max_length=200, null=True)),
                ('cpi', models.CharField(max_length=200, null=True)),
                ('precentage_10', models.CharField(max_length=200, null=True)),
                ('precentage_12', models.CharField(max_length=200, null=True)),
                ('resume', models.FileField(null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
