# Generated by Django 3.2.5 on 2021-10-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezyaplyapp', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='internships',
            name='intern_role',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
