# Generated by Django 3.2.5 on 2021-10-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezyaplyapp', '0009_internships_intern_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='user_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
