# Generated by Django 3.2.5 on 2021-10-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezyaplyapp', '0010_auto_20211009_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internships',
            name='cpi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internships',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internships',
            name='semester',
            field=models.IntegerField(null=True),
        ),
    ]
