# Generated by Selenium IDE
# import pytest
# import time
# import json
from selenium import webdriver
from selenium.webdriver.common.by import By
# from selenium.webdriver.common.action_chains import ActionChains
# from selenium.webdriver.support import expected_conditions
# from selenium.webdriver.support.wait import WebDriverWait
# from selenium.webdriver.common.keys import Keys
# from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

# class TestAddinternship():
#   def setup_method(self):
#     options = webdriver.ChromeOptions()    
# driver = webdriver.Chrome(executable_path="C:\webdrivers\chromedriver.exe",chrome_options=options)
# vars = {}
  
# #   def teardown_method(self):
# driver.quit()
  
# #   def test_addinternship(self):
# driver.get("http://ezzyaply.pythonanywhere.com/login/?next=/")
# driver.set_window_size(1552, 840)
# driver.find_element(By.ID, "your_name").click()
# driver.find_element(By.ID, "your_name").send_keys("admin")
# driver.find_element(By.CSS_SELECTOR, "figure").click()
# driver.find_element(By.ID, "your_pass").click()
# driver.find_element(By.ID, "your_pass").send_keys("admin")
# driver.find_element(By.ID, "signin").click()
# driver.find_element(By.LINK_TEXT, "Add Internship").click()
# driver.find_element(By.ID, "id_company_name").click()
# driver.find_element(By.ID, "id_company_name").send_keys("Siemens")
# driver.find_element(By.ID, "id_intern_role").click()
# driver.find_element(By.ID, "id_intern_role").send_keys("Deep Learning Developer")
# driver.find_element(By.ID, "id_description").click()
# driver.find_element(By.ID, "id_description").send_keys("Siemens work in field of deep learning.")
# driver.find_element(By.ID, "id_duration").click()
# driver.find_element(By.ID, "id_duration").send_keys("6")
# driver.find_element(By.ID, "id_cpi").click()
# driver.find_element(By.ID, "id_cpi").send_keys("7")
# driver.find_element(By.ID, "id_semester").click()
# driver.find_element(By.ID, "id_semester").send_keys("6")
# driver.find_element(By.ID, "id_stipend").click()
# driver.find_element(By.ID, "id_stipend").send_keys("50000")
# driver.find_element(By.ID, "id_date").click()
# driver.find_element(By.ID, "id_date").send_keys("09-11-2021 15:00")
# driver.find_element(By.ID, "id_other_qualifications").click()
# driver.find_element(By.ID, "id_other_qualifications").send_keys("Candidate should be good in coding and know how to train a deep learning model.")
# driver.find_element(By.CSS_SELECTOR, ".contact100-form-btn").click()
# driver.find_element(By.LINK_TEXT, "Logout").click()



  
# test=TestAddinternship()
# test.setup_method()
# test.test_addinternship()
# test.teardown_method()

options = webdriver.ChromeOptions()    
driver = webdriver.Chrome(executable_path="C:\webdrivers\chromedriver.exe",chrome_options=options)
driver.get("http://ezzyaply.pythonanywhere.com/login/?next=/")
driver.set_window_size(1552, 840)
driver.find_element(By.ID, "your_name").click()
driver.find_element(By.ID, "your_name").send_keys("admin")
# driver.find_element(By.CSS_SELECTOR, "figure").click().send_keys("admin")
# driver.find_element(By.ID, "your_pass").click()
driver.find_element(By.ID, "your_pass").click().send_keys("admin")
driver.find_element(By.ID, "signin").click()
driver.find_element(By.LINK_TEXT, "Add Internship").click()
driver.find_element(By.ID, "id_company_name").click().send_keys("Siemens")
# driver.find_element(By.ID, "id_company_name").send_keys("Siemens")
driver.find_element(By.ID, "id_intern_role").click().send_keys("Deep Learning Developer")
# driver.find_element(By.ID, "id_intern_role").send_keys("Deep Learning Developer")
driver.find_element(By.ID, "id_description").click().send_keys("Siemens work in field of deep learning.")
# driver.find_element(By.ID, "id_description").send_keys("Siemens work in field of deep learning.")
driver.find_element(By.ID, "id_duration").click().send_keys("6")
# driver.find_element(By.ID, "id_duration").send_keys("6")
driver.find_element(By.ID, "id_cpi").click().send_keys("7")
# driver.find_element(By.ID, "id_cpi").send_keys("7")
driver.find_element(By.ID, "id_semester").click().send_keys("6")
# driver.find_element(By.ID, "id_semester").send_keys("6")
driver.find_element(By.ID, "id_stipend").click().send_keys("50000")
# driver.find_element(By.ID, "id_stipend").send_keys("50000")
driver.find_element(By.ID, "id_date").click().send_keys("09-11-2021 15:00")
# driver.find_element(By.ID, "id_date").send_keys("09-11-2021 15:00")
driver.find_element(By.ID, "id_other_qualifications").click().send_keys("Candidate should be good in coding and know how to train a deep learning model.")
# driver.find_element(By.ID, "id_other_qualifications").send_keys("Candidate should be good in coding and know how to train a deep learning model.")
driver.find_element(By.CSS_SELECTOR, ".contact100-form-btn").click()
driver.find_element(By.LINK_TEXT, "Logout").click()
