# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDownloadresponses2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_downloadresponses2(self):
    self.driver.get("http://localhost:8000/login/")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.ID, "signin").click()
    self.driver.find_element(By.CSS_SELECTOR, ".row:nth-child(1) > div > a:nth-child(1) > img").click()
    self.driver.find_element(By.CSS_SELECTOR, "a:nth-child(1) > .btn").click()
    self.driver.close()
  
