# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddannouncement():
  def setup_method(self):
    options = webdriver.ChromeOptions()    
    self.driver = webdriver.Chrome(executable_path="C:\webdrivers\chromedriver.exe",chrome_options=options)
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_addannouncement(self):
    self.driver.get("http://localhost:8000/login/")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.ID, "your_name").click()
    self.driver.find_element(By.ID, "your_name").click()
    element = self.driver.find_element(By.ID, "your_name")
    element.send_keys("admin")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".signin-content").click()
    self.driver.find_element(By.ID, "your_pass").click()
    self.driver.find_element(By.ID, "your_pass").click()
    element = self.driver.find_element(By.ID, "your_pass")
    element.send_keys("admin")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "signin").click()
    self.driver.find_element(By.LINK_TEXT, "Make Announcement").click()
    self.driver.find_element(By.ID, "id_announcement_date").click()
    self.driver.find_element(By.ID, "id_announcement_date").click()
    self.driver.find_element(By.ID, "id_announcement_date").send_keys("02-11-2021")
    self.driver.find_element(By.ID, "id_announcement_text").click()
    self.driver.find_element(By.ID, "id_announcement_text").send_keys("Nobody is selected for Microsoft internship.")
    self.driver.find_element(By.CSS_SELECTOR, ".contact100-form-btn").click()
# cdc
test=TestAddannouncement()
test.setup_method()
test.test_addannouncement()