# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddinternship():
  def setup_method(self):
    options = webdriver.ChromeOptions()    
    self.driver = webdriver.Chrome(executable_path="C:\webdrivers\chromedriver.exe",chrome_options=options)
    self.vars = {}
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_addinternship(self):
    self.driver.get("http://localhost:8000/login/")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.ID, "your_name").click()
    self.driver.find_element(By.ID, "your_name").click()
    element = self.driver.find_element(By.ID, "your_name")
    element.send_keys("admin")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".signin-content").click()
    self.driver.find_element(By.ID, "your_pass").click()
    self.driver.find_element(By.ID, "your_pass").click()
    element = self.driver.find_element(By.ID, "your_pass")
    element.send_keys("admin")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "signin").click()
    self.driver.find_element(By.LINK_TEXT, "Add Internship").click()
    self.driver.find_element(By.ID, "id_company_name").click()
    self.driver.find_element(By.ID, "id_company_name").send_keys("Adobe")
    self.driver.find_element(By.ID, "id_intern_role").click()
    self.driver.find_element(By.ID, "id_intern_role").send_keys("Software Engineer")
    self.driver.find_element(By.ID, "id_description").click()
    # self.driver.find_element(By.ID, "id_description").send_keys("It is a ver")
    self.driver.find_element(By.ID, "id_description").click()
    self.driver.find_element(By.ID, "id_description").send_keys("Adobe Inc., originally called Adobe Systems Incorporated, is an American multinational computer software company. ")
    self.driver.find_element(By.ID, "id_duration").click()
    self.driver.find_element(By.ID, "id_duration").send_keys("2")
    self.driver.find_element(By.ID, "id_cpi").click()
    self.driver.find_element(By.ID, "id_cpi").send_keys("8")
    self.driver.find_element(By.ID, "id_semester").click()
    self.driver.find_element(By.ID, "id_semester").send_keys("6")
    self.driver.find_element(By.ID, "id_stipend").click()
    self.driver.find_element(By.ID, "id_stipend").send_keys("10000")
    self.driver.find_element(By.ID, "id_date").click()
    self.driver.find_element(By.ID, "id_date").send_keys("06-11-2021 16:00")
    self.driver.find_element(By.ID, "id_other_qualifications").click()
    self.driver.find_element(By.ID, "id_other_qualifications").send_keys("Person should be good at coding and problem solving.")
    self.driver.find_element(By.CSS_SELECTOR, ".contact100-form-btn").click()
  
test=TestAddinternship()
test.setup_method()
test.test_addinternship()
